[package]
name = "helloworld"
version = "0.1.0"
authors = ["eteplus <eteplus@outlook.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"] ## add this

[dependencies]
wasm-bindgen = "*" ## add this

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]